---
name: ansible-lint
on:
  pull_request:
    branches:
      - "main"
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v26.8.0
